version: "3.9"

services:
###
  # reverse proxy
  ###
  traefik:
    image: traefik:v2.6.1
    container_name: traefik
    ports:
      - '80:80'
      - '443:443'
      - '8888:8080'
    volumes:
      - ./traefik/certs/:/etc/certs/       
      - ./traefik/acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/conf.yml:/conf/conf.yaml  
      - ./traefik/traefik.yml:/etc/traefik/traefik.yaml
    networks:
      - instant

networks:
  instant:
    external: true
    name: instant_default