apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.cicd.yml convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: fhir
  name: fhir
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fhir
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.cicd.yml convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: fhir
    spec:
      containers:
        - image: hapiproject/hapi:v5.1.0
          name: hapi-fhir
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
