configMapGenerator:
  - name: opencr-configmap
    files:
      - ./volume/config_instant.json
      - ./volume/decisionRules.json
      - ./volume/mediator.json
resources:
  # volumes
  - elasticsearch-data-persistentvolumeclaim.yaml
  # deployments
  - es-deployment.yaml
  - opencr-deployment.yaml
  # services
  - es-service.yaml
  - opencr-service.yaml
