apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.cicd.yml convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: opencr
  name: opencr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: opencr
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.cicd.yml convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: opencr
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: cicd
            - name: HAPI_FHIR_URL
              value: http://hapi-fhir:8080/fhir/metadata
            - name: fhirServer__baseURL
              value: http://hapi-fhir:8080/fhir
          image: intrahealth/opencr
          name: opencr
          ports:
            - containerPort: 3000
          resources: {}
          volumeMounts:
            - mountPath: /src/server/config
              name: opencr-data
      restartPolicy: Always
      volumes:
        - name: opencr-data
          configMap:
            claimName: opencr-data
status: {}
