apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.cicd.yml convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: opencr
  name: opencr
spec:
  type: LoadBalancer
  # change to 3003 from default to avoid port contention
  ports:
    - name: "3003"
      port: 3003
      targetPort: 3000
  selector:
    io.kompose.service: opencr
# status:
#   loadBalancer: {}
