apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f instant/client/docker/docker-compose.yml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: opencr
  name: opencr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: opencr
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f instant/client/docker/docker-compose.yml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: opencr
    spec:
      initContainers:
        - name: setup-opencr-config
          image: busybox:1.28
          command: ['sh', '-c', 'cp -r /tmp/opencr-configmap/. /opencr-config']
          volumeMounts:
            - mountPath: /tmp/opencr-configmap
              name: opencr-configmap
            - mountPath: /opencr-config
              name: config
      containers:
        - env:
            - name: HAPI_FHIR_URL
              value: http://hapi-fhir-server-service:8080/fhir/metadata
            - name: NODE_ENV
              value: instant
            - name: fhirServer__baseURL
              value: http://hapi-fhir-server-service:8080/fhir
          image: intrahealth/opencr:6195bd8
          name: opencr
          ports:
            - containerPort: 3000
          resources: {}
          volumeMounts:
            - mountPath: /src/server/config
              name: config
      restartPolicy: Always
      volumes:
        - name: opencr-configmap
          configMap:
            name: opencr-configmap
        - name: config
          emptyDir: {}
status: {}
