apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: hearth
  name: hearth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hearth
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: hearth
    spec:
      containers:
      - env:
        - name: authentication__type
          value: disabled
        - name: logger__level
          value: warning
        - name: mongodb__url
          value: mongodb://mongo/hearth-dev
        image: intrahealth/hearth:latest
        imagePullPolicy: ""
        name: hearth-gofr
        ports:
        - containerPort: 3447
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
