apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openhim-mongo-volume-claim
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi