version: '3.3'

services:
  logstash:
    image: docker.elastic.co/logstash/logstash:7.12.1
    container_name: logstash
    volumes:
      - logstash-pipeline:/usr/share/logstash/pipeline/
      - logstash-config:/usr/share/logstash/config/

  fhir-extractor:
    image: jembi/fhir-extractor:v2.0.0
    container_name: fhir-extractor
    environment:
      - GET_URL=http://hapi-fhir:8080/fhir
      - POST_URL=http://logstash:5055/fhir
      - TRUST_SELF_SIGNED=true
      - OPENHIM_PASSWORD=instant101
      - OPENHIM_USERNAME=root@openhim.org
      - OPENHIM_URL=https://openhim-core:8080

volumes:
  logstash-pipeline:
    external: true
  logstash-config:
    external: true
