configMapGenerator:
  - name: mapper-config-importer-configmap
    files:
      - ./volume/openhim-import.json
      - ./volume/openhimConfig.js
  - name: mcsd-endpoint-importer-configmap
    files:
      - ./volume/endpoint.json
      - ./volume/endpoint.js
resources:
  - ./mapper-config-importer-job.yaml
  - ./mcsd-endpoint-importer-job.yaml
