apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: core-package
spec:
  selector:
    matchLabels:
      app: mongo
  serviceName: mongo
  replicas: 3
  template:
    metadata:
      labels:
        app: mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo
        image: mongo:4.2
        command:
          - mongod
          - "--bind_ip_all"
          - "--replSet"
          - mongo-set
        ports:
          - containerPort: 27017
        volumeMounts:
          - name: mongo-volume
            mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
