apiVersion: batch/v1
kind: Job
metadata:
  name: core-openhim-config-importer-job
  labels:
    app.kubernetes.io/name: openhim-config-importer
    app.kubernetes.io/instance: openhim-config-importer-1
    app.kubernetes.io/version: '0.1'
    app.kubernetes.io/component: config-importer
    app.kubernetes.io/part-of: core-package
spec:
  template:
    spec:
      containers:
        - name: openhim-config-importer
          image: jembi/instantohie-config-importer
          args:
            - sh
            - -c
            - wait-on -t 30000 https-get://openhim-core-service:8082/heartbeat && node openhimConfig.js
          env:
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: '0'
            - name: OPENHIM_API_HOSTNAME
              value: openhim-core-service
            - name: OPENHIM_API_PASSWORD
              value: openhim-password
            - name: OPENHIM_API_PORT
              value: '8082'
            - name: OPENHIM_API_USERNAME
              value: root@openhim.org
          volumeMounts:
            - mountPath: /importer
              name: core-openhim-config-importer-config
      restartPolicy: Never
      volumes:
        - name: core-openhim-config-importer-config
          configMap:
            name: core-openhim-config-importer-configmap
