apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hapi-fhir-server-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
      - hapi-fhir-server-dev.instant
  rules:
    - host: hapi-fhir-server-dev.instant
      http:
        paths:
        - path: /
          backend:
            serviceName: hapi-fhir-server-service
            servicePort: 8080
