kind: List
apiVersion: v1
items:
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: openhim-core
    spec:
      replicas: 1
      selector:
        matchLabels:
          name: core
      template:
        metadata:
          labels:
            name: core
        spec:
          containers:
          - name: openhim-core
            image: jembi/openhim-core:5
            env:
            - name: api_authenticationTypes
              value: '["token", "basic"]'
            - name: mongo_atnaUrl
              value: mongodb://mongo/openhim
            - name: mongo_url
              value: mongodb://mongo/openhim
            ports:
            - containerPort: 8080
            - containerPort: 5000
            - containerPort: 5001
            - containerPort: 5050
            - containerPort: 5051
            - containerPort: 5052
          restartPolicy: Always
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: mongo
    spec:
      replicas: 1
      selector:
        matchLabels:
          name: mongo
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            name: mongo
        spec:
          containers:
          - image: mongo:4.2
            name: openhim-mongo
            resources: {}
            volumeMounts:
            - mountPath: /data/db
              name: mongo-claim
          restartPolicy: Always
          volumes:
          - name: mongo-claim
            persistentVolumeClaim:
              claimName: mongo-claim
  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      labels:
      name: mongo-claim
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
    status: {}
