version: '3.7'

services:
  redis:
    container_name: redis-gofr
    image: redis
    ports:
      - "6379:6379"
    restart: always

  fhir:
    container_name: fhir
    image: hapiproject/hapi:v5.5.2
    ports:
      - "8092:8080"
    restart: always
    depends_on:
      - redis
    environment:
      - hapi.fhir.partitioning.enabled=true
      - hapi.fhir.partitioning.allow_references_across_partitions=false
      - hapi.fhir.partitioning.partitioning_include_in_search_hashes=false
      - hapi.fhir.enable_index_missing_fields=true
      - hapi.fhir.auto_create_placeholder_reference_targets=true
      - hapi.fhir.client_id_strategy=ANY
      - spring.jpa.properties.hibernate.search.enabled=true
      - spring.jpa.properties.hibernate.search.backend.type=lucene
      - spring.jpa.properties.hibernate.search.backend.analysis.configurer=ca.uhn.fhir.jpa.search.HapiLuceneAnalysisConfigurer
      - spring.jpa.properties.hibernate.search.backend.directory.type=local-filesystem
      - spring.jpa.properties.hibernate.search.backend.directory.root=target/lucenefiles
      - spring.jpa.properties.hibernate.search.backend.lucene_version=lucene_current
      # file:// can only deal with absolute paths, have to use classpath
    #   SPRING_CONFIG_LOCATION: 'classpath:./application.yaml'

  hapi-cli:
    container_name: hapi-cli
    image: intrahealth/hapi-fhir-cli:latest
    depends_on:
      - fhir
    command: /bin/sh -c "/upload-definitions.sh -p 8080 -h fhir"

  gofr:
    container_name: gofr
    image: intrahealth/gofr:latest
    environment:
      - mCSD__server__protocal=http
      - mCSD__server__host=fhir
      - mCSD__server__port=8080
      - mCSD__server__basePath=fhir
      - REDIS_HOST=redis
    ports:
      - "4000:4000"
    restart: always

# join core network
# networks:
#   default:
#     external: true
#     name: instant_default