apiVersion: v1
kind: Service
metadata:
  name: dhis-web
  labels:
    package: dhis
spec:
  type: LoadBalancer
  selector:
    component: dhis-web
  ports:
    - name: dhis-port-8081
      port: 8081
      targetPort: 8080
