apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dhis-postgres-volume-claim
  labels:
    package: dhis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
