version: '3.8'
 
services:
  openmrs-referenceapplication-mysql:
    restart: "always"
    image: mysql:5.6
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci"
    environment:
      MYSQL_DATABASE: ${MYSQL_DB:-openmrs}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-Admin123}
      MYSQL_USER: ${MYSQL_USER:-openmrs}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-Admin123}
    healthcheck:
      test: "exit 0"
    volumes:
      - openmrs-referenceapplication-mysql-data:/var/lib/mysql
      - openmrs-dbdump:/docker-entrypoint-initdb.d 

 
  openmrs-referenceapplication:
    restart: "always"
    image: openmrs/openmrs-reference-application-distro:qa
    depends_on:
      - openmrs-referenceapplication-mysql
    ports:
      - "8090:8080"
    environment:
      DB_DATABASE: ${MYSQL_DB:-openmrs}
      DB_HOST: openmrs-referenceapplication-mysql
      DB_USERNAME: ${MYSQL_USER:-openmrs}
      DB_PASSWORD: ${MYSQL_PASSWORD:-Admin123}
      DB_CREATE_TABLES: 'false'
      DB_AUTO_UPDATE: 'false'
      MODULE_WEB_ADMIN: 'true'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/openmrs/"]
      timeout: 20s
    volumes:
      - openmrs-referenceapplication-data:/usr/local/tomcat/.OpenMRS/
      - openmrs-modules:/usr/local/tomcat/.OpenMRS/modules/ # do not store modules in data
      - openmrs-owa:/usr/local/tomcat/.OpenMRS/owa/ # do not store owa in data
      - openmrs-ssl:/ssl/  #SSL certs for the EMR-LIS comunication
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=instant_default'
      - 'traefik.http.routers.openmrs.rule=Host(`instant.openelis-global.org`) && PathPrefix(`/openmrs`)'
      - 'traefik.http.routers.openmrs.tls=true'
      - 'traefik.http.routers.openmrs.tls.certresolver=myresolver'
      - 'traefik.http.routers.openmrs.entrypoints=https'
      - 'traefik.http.services.openmrs.loadbalancer.server.port=8080'
      - 'traefik.http.services.openmrs.loadbalancer.server.scheme=https'
      - 'traefik.http.routers.openmrs.service=openmrs'
    container_name: openmrs

volumes:
   openmrs-referenceapplication-mysql-data:
   openmrs-referenceapplication-data:
   openmrs-dbdump:
    external: true
   openmrs-modules:
    external: true 
   openmrs-owa:
    external: true
   openmrs-ssl:
    external: true    