version: '3.3'

services:
  mongo:
    container_name: openhim-mongo
    image: mongo:4.2
    volumes:
      - './data/mongo:/data/db'

  core:
    container_name: openhim-core
    image: jembi/openhim-core:5
    environment:
      - mongo_url=mongodb://mongo/openhim
      - mongo_atnaUrl=mongodb://mongo/openhim
    ports:
      - "8080:8080"
      - "5000:5000"
      - "5001:5001"
      - "5050:5050"
      - "5051:5051"
      - "5052:5052"
    depends_on:
      - mongo

  console:
    container_name: openhim-console
    image: jembi/openhim-console:1.13
    ports:
        - "9000:80"

  fhir:
    container_name: hapi-fhir
    image: hapiproject/hapi:4.1
    ports:
      - "3447:8080"
    # For mysql setup:
    # environment:
    #   - JAVA_OPTS='-Dhapi.properties=/usr/local/tomcat/conf/hapi.properties'
    # volumes:
    #   - ./hapi.properties:/usr/local/tomcat/conf/hapi.properties
    # depends_on:
    #   - mysql

  # HAPI FHIR with MYSQL is throwing an error right now so cannot be used:
  #   java.sql.SQLSyntaxErrorException: Specified key was too long; max key length is 3072 bytes
  # This seems to be an error in code that I cannot work around, we will need to wait for a fix.
  #
  # mysql:
  #   image: mysql:5.7
  #   container_name: hapi-mysql
  #   command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
  #   environment:
  #     MYSQL_DATABASE: 'hapi'
  #     MYSQL_USER: 'admin'
  #     MYSQL_PASSWORD: 'admin'
  #     MYSQL_ROOT_PASSWORD: 'admin'
  #   # add data volume
