version: '3.3'

services:
  mongo:
    container_name: openhim-mongo
    image: mongo:4.2
    volumes:
      - './data/mongo:/data/db'

  core:
    container_name: openhim-core
    image: jembi/openhim-core:5
    environment:
      - mongo_url=mongodb://mongo/openhim
      - mongo_atnaUrl=mongodb://mongo/openhim
      - api_authenticationTypes=["token", "basic"]
    ports:
      - "8080:8080"
      - "5000:5000"
      - "5001:5001"
      - "5050:5050"
      - "5051:5051"
      - "5052:5052"
    depends_on:
      - mongo

  console:
    container_name: openhim-console
    image: jembi/openhim-console:1.13
    ports:
        - "9000:80"

  fhir:
    container_name: hapi-fhir
    image: hapiproject/hapi:4.1
    ports:
      - "3447:8080"
    environment:
      - JAVA_OPTS='-Dhapi.properties=/usr/local/tomcat/conf/hapi.properties'
    volumes:
      - ./hapi.properties:/usr/local/tomcat/conf/hapi.properties
    depends_on:
      - mysql

  mysql:
    container_name: hapi-mysql
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_DATABASE: 'hapi'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin123'
      MYSQL_ROOT_PASSWORD: 'root123'
    # add data volume

  # container for executing a bash scripts for setting up the config for the relevant services
  config-importer:
    container_name: config-importer
    build:
      context: .
      dockerfile: Dockerfile.importer
    environment:
      OPENHIM_API_SERVER: 'https://openhim-core:8080'
      OPENHIM_API_USERNAME: 'root@openhim.org'
      OPENHIM_API_PASSWORD: 'openhim-password'
    volumes:
        - type: bind
          source: ./importer.sh
          target: /importer.sh
        - type: bind
          source: ./openhim-import.json
          target: /openhim-import.json
    command: 'sh importer.sh'
    # ensure all relevant services are running before executing the importer
    depends_on:
      - core
      - fhir
