version: '3.3'

services:
  mongo-1:
    image: mongo:4.2
    container_name: mongo-1
    volumes:
      - './data/mongo1:/data/db'
    ports:
      - "27017:27017"

  fhir:
    container_name: hapi-fhir
    image: hapiproject/hapi:v4.1.0
    ports:
      - "3447:8080"

  mysql:
    container_name: hapi-mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
