version: '3.3'

services:
  # container for executing config import scripts for setting up initial config
  config-importer:
    container_name: openhim-config-importer
    build:
      context: importer
      dockerfile: Dockerfile
    environment:
      OPENHIM_API_HOSTNAME: 'openhim-core'
      OPENHIM_API_PORT: 8080
      OPENHIM_API_USERNAME: 'root@openhim.org'
      OPENHIM_API_PASSWORD: 'instant101'
      # Reject unauthorised is only needed if the OpenHIM's SSL is not setup
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    volumes:
      - type: bind
        source: ./importer/volume
        target: /importer
    # This command will only attempt to import the OpenHIM config when the heartbeat responds with a 2xx
    command: sh -c "wait-on -t 30000 https-get://openhim-core:8080/heartbeat && node openhimConfig.js"
    # ensure all relevant services are running before executing the importer
    depends_on:
      - core
      - fhir
