apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: config-importer
  name: config-importer
spec:
  containers:
  - args:
    - sh
    - -c
    - wait-on -t 30000 https-get://openhim-core:8080/heartbeat && node openhimConfig.js
    env:
    - name: NODE_TLS_REJECT_UNAUTHORIZED
      value: "0"
    - name: OPENHIM_API_HOSTNAME
      value: openhim-core
    - name: OPENHIM_API_PASSWORD
      value: openhim-password
    - name: OPENHIM_API_PORT
      value: "8080"
    - name: OPENHIM_API_USERNAME
      value: root@openhim.org
    image: jembi/instantohie-config-importer
    name: instantohie-config-importer
    resources: {}
    volumeMounts:
    - mountPath: /importer
      name: config-importer-claim0
  restartPolicy: Never
  volumes:
  - name: config-importer-claim0
    persistentVolumeClaim:
      claimName: config-importer-claim0
status: {}
