apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f packages/data-analytics/docker/docker-compose.elastic.yml -o packages/data-analytics/kubernetes/main/
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: kibana
  name: kibana
spec:
  type: LoadBalancer
  ports:
    - name: "5601"
      port: 5601
      targetPort: 5601
  selector:
    io.kompose.service: kibana
status:
  loadBalancer: {}
