apiVersion: v1
kind: Service
metadata:
  name: hapi-fhir-server-service
  namespace: core-component
spec:
  type: LoadBalancer
  selector:
    component: hapi-fhir-server
  ports:
    - name: hapi-fhir-server-8080
      port: 8080
      targetPort: 8080
