apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hapi-fhir-mysql-volume-claim
  labels:
    package: core
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
