apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hapi-fhir-server-volume-claim
  namespace: core-package
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
