apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hapi-fhir-mysql-volume-claim
  namespace: core-component
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
