apiVersion: apps/v1
kind: Deployment
metadata:
  name: mapper-deployment
  namespace: healthworkforce-component
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mapper
  template:
    metadata:
      labels:
        component: mapper
    spec:
      initContainers:
        - name: check-openhim-status
          image: busybox:1.28
          command: ['sh', '-c', 'until telnet openhim-core-service.core-component 8082; do echo OpenHIM not running yet; sleep 10; done;']
      containers:
        - name: mapper
          image: jembi/openhim-mediator-mapping:v0.1.0
          ports:
            - containerPort: 3003
          volumeMounts:
            - name: healthworkforce-mapper-volume-dhis1
              mountPath: /app/endpoints/dhis2part1
            - name: healthworkforce-mapper-volume-dhis2
              mountPath: /app/endpoints/dhis2part2
          env:
            - name: OPENHIM_URL
              value: https://openhim-core-service.core-component:8082
            - name: OPENHIM_USERNAME
              value: root@openhim.org
            - name: OPENHIM_PASSWORD
              value: instant101
      volumes:
        - name: healthworkforce-mapper-volume-dhis1
          configMap:
            name: healthworkforce-mapper-configmap-dhis1
        - name: healthworkforce-mapper-volume-dhis2
          configMap:
            name: healthworkforce-mapper-configmap-dhis2
