apiVersion: v1
kind: Service
metadata:
  name: mcsd-mediator-service
  labels:
    package: hwf
spec:
  type: LoadBalancer
  selector:
    component: mcsd-mediator
  ports:
    - name: mcsd-mediator-3003
      port: 3003
      targetPort: 3003
