apiVersion: v1
kind: Service
metadata:
  name: mock-service
  labels:
    package: hwf
spec:
  type: LoadBalancer
  selector:
    component: mock-service
  ports:
    - name: mock-service
      port: 4000
      targetPort: 4000
