apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: facility-recon
  name: facility-recon
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: facility-recon
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: facility-recon
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: mongo
        - name: HEARTH_URL
          value: http://hearth:3447
        - name: REDIS_HOST
          value: redis
        image: openhie/facility-recon:latest
        imagePullPolicy: ""
        name: facility-recon
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
