version: '3.3'

services:
  opencr:
    container_name: opencr
    image: intrahealth/opencr:ef90a5a
    # change to 3004 to avoid port contention
    ports:
      - "3004:3000"
    depends_on:
      - es
    restart: always
    environment:
      - NODE_ENV=instant
      - HAPI_FHIR_URL=http://hapi-fhir:8080/fhir/metadata
      - fhirServer__baseURL=http://hapi-fhir:8080/fhir
    volumes:
      - opencr-data:/src/server/config

  es:
    container_name: es
    image: intrahealth/elasticsearch:latest
    environment:
      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  opencr-data:
    external: true
  elasticsearch-data:
    driver: local
