configMapGenerator:
  - name: core-openhim-core-configmap
    files:
      - ./openhim/volume/openhim-core/development.json

resources:
  # volumes
  - ./hapi-fhir/hapi-fhir-mysql-volume-claim.yaml
  # deployments
  - ./hapi-fhir/hapi-fhir-mysql-deployment.yaml
  - ./hapi-fhir/hapi-fhir-server-deployment.yaml
  - ./openhim/openhim-core-deployment.yaml
  # services
  - ./hapi-fhir/hapi-fhir-mysql-service.yaml
  - ./hapi-fhir/hapi-fhir-server-service.yaml
  - ./openhim/openhim-core-service.yaml
