apiVersion: v1
kind: Service
metadata:
  name: openhim-console-service
spec:
  type: LoadBalancer
  selector:
    component: openhim-console
  ports:
    - name: console-80
      port: 80
      targetPort: 80
